app/views/scraping/models.py
from app import *
from sqlalchemy import *
from sqlalchemy.orm import (scoped_session, sessionmaker, relationship,
                            backref)
from sqlalchemy.ext.declarative import declarative_base
engine = create_engine('sqlite:///database.sqlite3', convert_unicode=True)

engine = create_engine('postgresql://'+app.config['DBUSER']+':'+app.config['PASSWORD']+'@'+app.config['HOST']+':5432/'+app.config['DBNAME'])
db_session = scoped_session(sessionmaker(autocommit=False,
                                         autoflush=False,
                                         bind=engine))

class Products(db.Model):
    pid = db.Column(db.String(300), primary_key=True)
    name = db.Column(db.String(300))
    url = db.Column(db.Text)

    def __repr__(self):
        return '<Product %r>' % self.pid

class Reviews(db.Model):
    __tablename__ = 'reviews'
    id= db.Column(db.Integer,primary_key=True, autoincrement = True)
    pid = db.Column(db.String(300),db.ForeignKey('products.pid'))
    text = db.Column(db.Text)
    title = db.Column(db.String(300))
    polarity = db.Column(db.Float)
    date = db.Column(db.Date)

    def __repr__(self):
        return '<Reviews %r>' % self.title

app/__init__.py
import os
from flask import Flask, request, render_template, flash, redirect, url_for, session, Blueprint
from tempfile import mkdtemp
import psycopg2
from flask_session import Session
from functools import wraps
import requests
import json
from flask_sqlalchemy import SQLAlchemy
from flask_graphql import GraphQLView

app = Flask(__name__, instance_path=os.path.join(os.path.abspath(os.curdir), 'instance'), instance_relative_config=True, static_url_path="", static_folder="static")
app.config.from_pyfile('config.cfg')

app.config['SESSION_FILE_DIR'] = mkdtemp()
Session(app)
con = psycopg2.connect(dbname=app.config['DBNAME'],user=app.config['DBUSER'],host=app.config['HOST'],password=app.config['PASSWORD'])

DB_URL = 'postgresql+psycopg2://{user}:{pw}@{url}/{db}'.format(user=app.config['DBUSER'],pw=app.config['PASSWORD'],url=app.config['URL'],db=app.config['DBNAME'])
app.config['SQLALCHEMY_DATABASE_URI'] = DB_URL
db = SQLAlchemy(app)

from app.views.scraping import models
from app.views.scraping.models import db_session
from app.views.scraping.schema import schema, Products


app.add_url_rule(
    '/graphql',
    view_func=GraphQLView.as_view(
        'graphql',
        schema=schema,
        graphiql=True # for having the GraphiQL interface
    )
)

@app.teardown_appcontext
def shutdown_session(exception=None):
    db_session.remove()

def execute_db(query,args=()):
    cur = con.cursor()
    cur.execute(query,args)
    con.commit()
    cur.close()
def query_db(query,args=(),one=False):
    cur = con.cursor()
    result=cur.execute(query,args)
    values=cur.fetchall()
    return values

def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if session.get("adminid") is None:
            return redirect(url_for("auth.login"))
        return f(*args, **kwargs)
    return decorated_function

def admin_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if session.get("admin")==False:
            return redirect(url_for("main.index", next=request.url))
        return f(*args, **kwargs)
    return decorated_function
    
# Importing Blueprints
from app.views.main import main
from app.views.scraping.flipkart import flipkart
from app.views.scraping.amazon import amazon
# Registering Blueprints
app.register_blueprint(main)
app.register_blueprint(flipkart)
app.register_blueprint(amazon)

app/views/graphql.py
import graphene

class Query(graphene.ObjectType):
    hello = graphene.String(argument=graphene.String(default_value="stranger"))

    def resolve_hello(self, info, argument):
        return 'Hello ' + argument

schema = graphene.Schema(query=Query)

result = schema.execute('{ hello }')
print(result.data['hello']) 

app/views/main.py
from flask import Flask, request, flash, render_template, flash, redirect, url_for, session, Blueprint
from flask_session import Session
from app import *
import requests
import urllib.request, json

main = Blueprint('main', __name__)


@main.route("/", methods=['POST', 'GET'])
def index():
    return render_template("home.html")

@main.route("/search", methods=['POST', 'GET'])
def search():
    if request.method=="POST":
        return redirect(url_for('flipkart.getResults', q=request.form['search_query']))
    return render_template("search.html", **locals())


@main.route("/reviews/<string:pid>", methods=['POST', 'GET'])
def reviews(pid):
    url = 'http://0.0.0.0:4000'+url_for('flipkart.getReviews', pid=pid)
    reviews = requests.get(url, verify=False).json()
    print(reviews)
    positive = reviews['positive']
    negative = reviews['negative']
    neutral = reviews['neutral']
    slightly_positive = reviews['slightly_positive']
    slightly_negative = reviews['slightly_negative']
    reviews = reviews['results']

    return render_template("reviews.html",**locals())

app/views/scraping/main.py
from flask import Flask, request, flash, render_template, flash, redirect, url_for, session, Blueprint,jsonify
import requests
import urllib.request, json

def saveReviews(pid):
    url = 'http://0.0.0.0:4000'+url_for('flipkart.getReviews', pid=pid)
    app = requests.get(url, verify=False)
    return "success"

app/templates/amazon.html
{%if reviews %}

{% for title,text in data %}
<b>{{title}}</b><br>
{{text}}<br><br>
{% endfor%}

{% endif %}

{% if results %}
{% for title,url in data %}
    {{title}}<br>
    {{url}}<br><br>
{% endfor %}
{% endif %}

app/templates/blob.html
{% if review %}
    {% for i,j,k in reviews %}
        <ol>{{loop.index}}.
        <b>{{i}}</b><br>
        {{j}}<br><br>
        {{k}}
        </ol>
    {% endfor %}
{% endif %}

app/templates/flipkart.html
{% if review %}
    {% for title,text,created in reviews %}
        <ol>{{loop.index}}.
        <b>{{title}}</b><br>
        {{text}}<br>
        <sub>{{created}}</sub><br><br>
        </ol>
    {% endfor %}
{% endif %}


{% if results %}
    {% for name,pid,url,tv in data %}
    <ol>{{loop.index}}.
    <b><a href="{{url_for('flipkart.getReviews',pid=pid)}}">{{name}}</a></b><br>
    <a href="{{url}}">Product Link : </a><br><br>
    Trusted Value: {{tv}}
    </ol>
    {% endfor %}
{% endif %}

app/templates/index.html
{% extends 'layouts.html' %}

{% block main %}

HELLO WORLD

{% endblock %}

app/templates/layouts.html
<!DOCTYPE html>
<html lang="en">
<meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->
<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="../assets/img/favicon.png">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    SentiENT
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!-- Extra details for Live View on GitHub Pages -->
  <!-- Canonical SEO -->
  <link rel="canonical" href="http://www.creative-tim.com/product/paper-dashboard-2-pro.html" />
  <!--     Fonts and icons     -->
  <link href="http://fonts.googleapis.com/css1a80.css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
  <!-- CSS Files -->
  <link href="/assets/css/bootstrap.min.css" rel="stylesheet" />
  <link href="/assets/css/paper-dashboard.min790f.css?v=2.0.1" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="/assets/demo/demo.css" rel="stylesheet" />
</head>

<body class="">
  <!-- End Google Tag Manager (noscript) -->
  <div class="wrapper ">
    <div class="sidebar" data-color="brown" data-active-color="danger">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
    -->
      <div class="logo">
        <a href="#" class="simple-text logo-normal text-center">
          SentiEnt
          <!-- <div class="logo-image-big">
            <img src="../assets/img/logo-big.png">
          </div> -->
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li {% if request.path == url_for('main.index') %}class="active"{% endif %}>
            <a href="{{ url_for('main.index') }}">
              <i class="nc-icon nc-bank"></i>
              <h5>Dashboard</h5>
            </a>
          </li>
          <li {% if request.path == url_for('main.search') %}class="active"{% endif %}>
            <a href="{{ url_for('main.search') }}">
              <i class="nc-icon nc-zoom-split"></i>
              <h5>Search</h5>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="#">SentiENT- Analysing reviews of products and services to present the best statistics.</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
        </div>
      </nav>
      <!-- End Navbar -->
      <!-- <div class="panel-header">

  <canvas id="bigDashboardChart"></canvas>


</div> -->
      <div class="content">
        {% block main %}
        {% endblock %}
      </div>

      <footer class="footer footer-black  footer-white ">
        <div class="container-fluid">
          <div class="row">
            <nav class="footer-nav">
              <ul>
                <li>
                  <a href="#">Home</a>
                </li>
              </ul>
            </nav>
            <div class="credits ml-auto">
              <span class="copyright">
                ©
                <script>
                  document.write(new Date().getFullYear())
                </script>, Made with <i class="fa fa-heart heart"></i> by __init__
              </span>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </div>
  <!--   Core JS Files   -->
  <script src="/assets/js/core/jquery.min.js"></script>
  <script src="/assets/js/core/popper.min.js"></script>
  <script src="/assets/js/core/bootstrap.min.js"></script>
  <script src="/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
  <script src="/assets/js/plugins/moment.min.js"></script>
  <!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
  <script src="/assets/js/plugins/bootstrap-switch.js"></script>
  <!--  Plugin for Sweet Alert -->
  <script src="/assets/js/plugins/sweetalert2.min.js"></script>
  <!-- Forms Validations Plugin -->
  <script src="/assets/js/plugins/jquery.validate.min.js"></script>
  <!--  Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->
  <script src="/assets/js/plugins/jquery.bootstrap-wizard.js"></script>
  <!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
  <script src="/assets/js/plugins/bootstrap-selectpicker.js"></script>
  <!--  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->
  <script src="/assets/js/plugins/bootstrap-datetimepicker.js"></script>
  <!--  DataTables.net Plugin, full documentation here: https://datatables.net/    -->
  <script src="/assets/js/plugins/jquery.dataTables.min.js"></script>
  <!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
  <script src="/assets/js/plugins/bootstrap-tagsinput.js"></script>
  <!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
  <script src="/assets/js/plugins/jasny-bootstrap.min.js"></script>
  <!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->
  <script src="/assets/js/plugins/fullcalendar.min.js"></script>
  <!-- Vector Map plugin, full documentation here: http://jvectormap.com/documentation/ -->
  <script src="/assets/js/plugins/jquery-jvectormap.js"></script>
  <!--  Plugin for the Bootstrap Table -->
  <script src="/assets/js/plugins/nouislider.min.js"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB2Yno10-YTnLjjn_Vtk0V8cdcY5lC4plU"></script>
  <!-- Place this tag in your head or just before your close body tag. -->
  <script async defer src="http://buttons.github.io/buttons.js"></script>
  <!-- Chart JS -->
  <script src="/assets/js/plugins/chartjs.min.js"></script>
  <!--  Notifications Plugin    -->
  <script src="/assets/js/plugins/bootstrap-notify.js"></script>
  <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="/assets/js/paper-dashboard.min790f.js?v=2.0.1" type="text/javascript"></script>
  <!-- Paper Dashboard DEMO methods, don't include it in your project! -->
  <script src="/assets/demo/demo.js"></script>
  <!-- Sharrre libray -->
  <script src="/assets/demo/jquery.sharrre.js"></script>
  <script>
    $(document).ready(function() {
      ctx = document.getElementById('chartEmail').getContext("2d");

      myChart = new Chart(ctx, {
        type: 'pie',
        data: {
          labels: ['Positive','Slightly Positive','Negative','Slightly Negative','Neutral'],
          datasets: [{
            label: "Reviews",
            pointRadius: 0,
            pointHoverRadius: 0,
            backgroundColor: [
              '#4acccd',
              '#EDD99F',
              '#BB9F7D',
              '#fcc468',
              '#e3e3e3'
            ],
            borderWidth: 0,
            data: [{{ positive }}, {{ slightly_positive }}, {{ negative }}, {{ slightly_negative }}, {{ neutral }}]
          }]
        },
        options: {

          legend: {

            display: false
          },

          tooltips: {
            enabled: true
          },

          scales: {
            yAxes: [{

              ticks: {
                display: false
              },
              gridLines: {
                drawBorder: false,
                zeroLineColor: "transparent",
                color: 'rgba(255,255,255,0.05)'
              }

            }],

            xAxes: [{
              barPercentage: 1.6,
              gridLines: {
                drawBorder: false,
                color: 'rgba(255,255,255,0.1)',
                zeroLineColor: "transparent"
              },
              ticks: {
                display: false,
              }
            }]
          },
        }
      });
    });
  </script>
</body>


</html>

app/templates/results.html
{% extends 'layouts.html' %}

{% block main %}
<div class="col-md-12">
  <div class="card">
    <div class="card-header">
      <h4 class="card-title"> Search results for '{{query}}' </h4>
    </div>
    <div class="card-body">
        <table class="table">
          <thead class="">
            <tr>
              <th></th>
              <th class="text-center">
                Product
              </th>
              <th></th>
              <th></th>
              <th class="text-right">
                Positive Reviews
              </th>
            </tr>
          </thead>
          <tbody>
                {% for i in range(pids|length) %}
                <tr>
                  <td>
                  </td>
                  <td class="text-center">
                    <a href="{{url_for('main.reviews',pid=pids[i])}}">{{p_name[i]}}</a>
                    <br>
                    <small><a href="{{ p_url[i] }}">Product Link : </a><br><br></small>
                  </td>
                  <td>
                  </td>
                  <td>
                  </td>
                  <td class="text-right"> <b>
                    {% if polarities[i]|count !=0%}
                      {% if polarities[i]|sum / polarities[i]|count  >=0 %}
                        {{ (polarities[i]|sum / polarities[i]|count)|round(1) *100}}% <br>
                      {% else %}
                        {{ (100 - polarities[i]|sum / polarities[i]|count) | round(1)*100}}%
                      {% endif %}
                    {% endif %}
                  </b>
                  </td>
                </tr>
                {% endfor %}
          </tbody>
        </table>
    </div>
  </div>
</div>

{% endblock %}

app/templates/reviews.html
{% extends 'layouts.html' %}

{% block main %}
    <div class ="row ">
      <div class="col-md-4">
        
      </div>
      <div class="col-md-4 ">
        <div class="card ">
          <div class="card-header ">
            <h5 class="card-title">Review Statistics</h5>
            <p class="card-category">Analysis based on User Reviews</p>
          </div>
          <div class="card-body ">
            <canvas id="chartEmail" class="ct-chart ct-perfect-fourth" width="456" height="300"></canvas>
          </div>
          <div class="card-footer ">
            <hr>
            <div class="stats">
              <i class="fa fa-calendar"></i> Number of reviews: {{ reviews|length }}
            </div>
          </div>
        </div>
      </div>

      <!-- <div class="col-md-6">
        <div class="card card-chart">
          <div class="card-header">
            <h5 class="card-title"> Trend Analysis </h5>
            <p class="card-category"> Changing public opinion with time </p>
          </div>
          <div class="card-body">
            <canvas id="activeUsers" class="ct-chart ct-perfect-fourth" width="456" height="300"></canvas>
          </div>
        </div>
      </div>
          </div> -->


    <div class="col-md-12">
      <div class="card card-plain">
        <div class="card-header text-center">
          <h4 class="card-title"> User Reviews </h4>
          <p class="card-category"> Here's what people thinks!!!</p>
        </div>
        <div class="card-body">
            <table class="table">
              <thead class="text-center">
                <th>
                  Review
                </th>
                <th class="text-right">
                  Trust Status
                </th>
              </thead>
              <tbody>
                  {% if reviews %}
                      {% for review in reviews %}
                        <tr>
                          <td> <b> {{ review[0]['title'] }} </b> - {{ review[0]['text'] }}</td>
                          <td class="text-right">
                            {% if review[0]['polarity'] %}
                              {% if review[0]['polarity'] > 0.5 %}
                                Positive
                              {% elif review[0]['polarity'] < -0.5 %}
                                Negative
                               {% elif review[0]['polarity'] >0 %}
                                Slightly Positive
                                {% elif review[0]['polarity'] < 0 %}
                                Slightly Negative
                              {% else %}
                                Neutral
                              {% endif %}
                            {% else %}
                              Not Calculated
                            {% endif %}
                          </td>
                        </tr>
                      {% endfor %}
                  {% endif %}
              </tbody>
            </table>
        </div>
      </div>
    </div>
{% endblock %}

app/templates/search.html
{% extends 'layouts.html' %}

{% block main %}
<form action="{{ url_for('main.search') }}" method="post">
  <div class="card">
    <div class="card-header ">
      <h4 class="card-title"> Search </h4>
    </div>
    <div class="card-body">
      <div class="col-md-6">
        <div class="input-group no-border">
          <input type="text" name="search_query" class="form-control" placeholder="Enter Product Name or Category...">
          <div class="input-group-append">
            <div class="input-group-text">
              <i class="nc-icon nc-zoom-split" type="submit"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}